/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class FRM_Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Instrucciones
     */
    public FRM_Instrucciones() {
        initComponents();
        inhabilitarInstrucciones();
        setLocationRelativeTo(this);
    }

    public void inhabilitarInstrucciones()
    {
        jta_Instrucciones.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Instrucciones = new javax.swing.JTextArea();

        setTitle("Instrucciones");

        jta_Instrucciones.setColumns(20);
        jta_Instrucciones.setForeground(new java.awt.Color(0, 153, 0));
        jta_Instrucciones.setRows(5);
        jta_Instrucciones.setText("\tInstrucciones del Juego\n\nAyuda a Homero a correr por Sprinfield!!\nSe fue a caminar y dejó los frijoles en la cocina!!\nPero ten cuidado, porque hay vehículos en el \ncamino, esquivalos con las flechas de arriba y abajo.\n\n\tBuena Suerte!");
        jta_Instrucciones.setCaretColor(new java.awt.Color(102, 255, 153));
        jScrollPane1.setViewportView(jta_Instrucciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jta_Instrucciones;
    // End of variables declaration//GEN-END:variables
}
