/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class FRM_MejoresJugadores extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MejoresJugadores
     */
    public FRM_MejoresJugadores() {
        initComponents();
        this.setSize(350, 300);
        setLocation(500, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMejoresJug = new javax.swing.JLabel();
        jl_PrimerLugar = new javax.swing.JLabel();
        txtPrimerLugar = new javax.swing.JTextField();
        fondoMejorJugador = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jlMejoresJug.setText("                                  Mejores Jugadores");
        getContentPane().add(jlMejoresJug);
        jlMejoresJug.setBounds(4, 5, 290, 30);

        jl_PrimerLugar.setText("Maria");
        getContentPane().add(jl_PrimerLugar);
        jl_PrimerLugar.setBounds(40, 55, 50, 20);

        txtPrimerLugar.setEditable(false);
        txtPrimerLugar.setText("1400 metros");
        getContentPane().add(txtPrimerLugar);
        txtPrimerLugar.setBounds(130, 49, 110, 30);
        getContentPane().add(fondoMejorJugador);
        fondoMejorJugador.setBounds(0, 0, 290, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoMejorJugador;
    private javax.swing.JLabel jlMejoresJug;
    private javax.swing.JLabel jl_PrimerLugar;
    private javax.swing.JTextField txtPrimerLugar;
    // End of variables declaration//GEN-END:variables
}
